# Generated by Django 4.1.7 on 2023-03-27 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='following_count',
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
